### ISSUE TITLE
.getFullYear() Is not a function quando viene creato il client Rest 

### ISSUE THREAD

**Issue by Fabio53443** [47PADO47/Classeviva.js#17]
Ciao!
Sono l'autore di una utility Node.js che copia i compiti da classeviva a Notion ed utilizzo la tua libreria per il fetching dell'agenda da cvv.
(https://github.com/Fabio53443/CVVtoNotion),

A fine giugno sembrava funzionare tutto, riprendo il codice in ieri e mi da errori legati alla libreria.
Nello specifico, quando creo il client Rest, ricevo questo errore:

```js
TypeError: date.getFullYear is not a function
    at #formatDate (C:\Users\Fabio\Desktop\CVVtoNotion\CVVtoNotion\node_modules\classeviva.js\dist\src\classes\Rest.js:600:27)
    at Rest.getAgenda (C:\Users\Fabio\Desktop\CVVtoNotion\CVVtoNotion\node_modules\classeviva.js\dist\src\classes\Rest.js:161:90)
    at agendafun (file:///C:/Users/Fabio/Desktop/CVVtoNotion/CVVtoNotion/src/main.js:66:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Users/Fabio/Desktop/CVVtoNotion/CVVtoNotion/src/main.js:149:14

Node.js v18.17.1
```
Questo è il mio codice dove si verifica l'errore:
```js
async function agendafun() {
  console.log("Fetching agenda...");
  await classeviva.login();
  let today = new Date().toISOString().split("T")[0];
  let nextMonth = new Date();
  nextMonth.setMonth(nextMonth.getMonth() + 1);
  nextMonth = nextMonth.toISOString().split("T")[0];
  let agenda = await classeviva.getAgenda("all", today, nextMonth);
  fs.writeFileSync("agenda.json", JSON.stringify(agenda));
  setTimeout(() => {
    classeviva.logout();
  }, 3500);
  console.log("Fetched agenda!");
  return agenda;
}
```

Questo è il codice nel modulo che il debugger segna:
```js
    /**
     * @private Formats date to string in format YYYYMMDD
     * @param {Date} date date to format
     * @returns {string} date in format YYYYMMDD
     */
    #formatDate(date = new Date()) {
        const year = date.getFullYear();
        const month = date.getMonth() + 1;
        const day = date.getDate();
        return `${year}${month < 10 ? "0" + month : month}${day < 10 ? "0" + day : day}`;
    }

```

Grazie!

**Comment by Fabio53443** [comment]
Trovato l'errore nel mio codice! scusa il disturbo.
